config/routes.rb
Testproy::Application.routes.draw do 
  root :to => "Products#list", :as => 'root'

  
  resources :locations

  match 'products/show_shopping_cart' => 'Products#show_shopping_cart', :as => 'show_shopping_cart'
  match 'products/add_item/:id' => 'Products#add_item', :as => 'add_item'
  match 'products/update_item/:id/:quantity' => 'Products#update_item', :as => 'update_item'
  match 'products/delete_item/:id' => 'Products#delete_item', :as => 'delete_item'
  match 'products/update_shopping_cart' => 'Products#update_shopping_cart', :as => 'update_shopping_cart'

  resources :products

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :location_id, :name
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category, :description, :name, :price, :quantity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, :notice => 'Location was successfully created.' }
        format.json { render :json => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.json { render :json => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, :notice => 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def update_shopping_cart
    str = params[:message]
    logger.debug "WEBON DE MIERDA: #{str}"

    products_array = str.split('|')

    session[:products].each do |session_product|
      products_array.each do |pa|
        values = pa.split(',')
        id = values[0]
        qty = values[1]

        if id.to_i == session_product.id
          session_product.quantity = qty.to_i
          break
        end

      end
    end


    # Set the modified quantity by the user to the session
    #session[:products].each do |session_product|
    #  product_array.each do |pa|
    #    if pa == session_product.id
    #      session_product.quantity = pa.quantity
    #      logger.debug 'ENTRO GARCA D MIERDA'
    #      break
    #    end
    #  end
    #end

    # Redirect to shopping_cart
    redirect_to '/products/show_shopping_cart'

  end

  def update_item
    logger.debug "PARAM ID: #{params[:id].to_s}"
    logger.debug "PARAM QTY: #{params[:quantity].to_s}"

    session[:products].each do |session_product|
      if session_product.id.to_s == params[:id].to_s
        logger.debug "ENTRO WEBON"
        logger.debug "ANTES :#{session_product.quantity}"
        logger.debug "VALOR: #{params[:quantity].to_i}"
        session_product.quantity = params[:quantity].to_i
        logger.debug "DESPUES :#{session_product.quantity}"
        break
      end
    end

    # Redirect to shopping_cart
    redirect_to '/products/show_shopping_cart'
  end

  def delete_item
    @product = nil
    logger.debug "Size before: #{session[:products].length}"
    logger.debug "Param ID: " + params[:id].to_s
    session[:products].each do |p|
      logger.debug "Each ID: " + p.id.to_s
      if p.id.to_s == params[:id]
        @product = p
        
        break
      end
    end

    # Delete the selected item
    session[:products].delete(@product)

    logger.debug "Size after: #{session[:products].length}"

    # Redirect to shopping_cart
    redirect_to '/products/show_shopping_cart'

  end

  def add_item

    # Create the shopping cart array
    if session[:products].nil?
      session[:products] = []
    end

    # Get the product
    @product = Product.find(params[:id])

    # Add one product by default
    @product.quantity = 1

    session[:products] << @product

    # Redirect to shopping_cart
    redirect_to '/products/show_shopping_cart'
  end

  def show_shopping_cart

    @items = session[:products]

    # Redirect
    respond_to do |format|
      format.html # shopping_cart.html.erb
    end

  end

  def list
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, :notice => 'Product was successfully created.' }
        format.json { render :json => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, :notice => 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html>
<head>
  <title>Testproy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--<link rel="stylesheet" type="text/css" href="../../assets/javascripts/bootstrap/css/bootstrap-responsive.css" />
  <link rel="stylesheet" type="text/css" href="../../assets/javascripts/bootstrap/css/bootstrap-responsive.min.css" />
  <link rel="stylesheet" type="text/css" href="../../assets/javascripts/bootstrap/css/bootstrap.css" />
  <link rel="stylesheet" type="text/css" href="../../assets/javascripts/bootstrap/css/bootstrap.min.css" />-->
</head>
<body>
	<div class="div-center">
		<%= yield %>
	</div>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.text_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<form action="/locations/maintain/" method="post" >
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
  <% @locations.each do |location| %>
    <tr>
      <td><%= location.name %></td>
      <td><%= location.location_id %></td>
      <!--<td><%= button_tag 'Show', :name => 'submit', :value => 'show', :class => 'btn btn-success' %></td>
      <td><%= button_tag 'Edit', :name => 'submit', :value => 'edit', :class => 'btn btn-warning' %></td>
      <td><%= button_tag 'Destroy', :name => 'submit', :value => 'destroy', :class => 'btn btn-danger' %></td>-->

      <td><%= link_to 'Show', location, :class => 'btn btn-success' %></td>
      <td><%= link_to 'Edit', edit_location_path(location), :class => 'btn btn-warning' %></td>
      <td><%= link_to 'Destroy', location, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger' %></td>

    </tr>
  <% end %>
    </tbody>
  </table>

  <br />

  <%= link_to 'New Location', new_location_path, :class => 'btn btn-info' %>
</form>

app/views/locations/list.html.erb
<h1>Listing locations</h1>

<form action="/locations/maintain/" method="post" >
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
  <% @locations.each do |location| %>
    <tr>
      <td><%= location.name %></td>
      <td><%= location.location_id %></td>
      <td><%= link_to 'Show', :name => 'submit', :value => 'show', :class => 'btn btn-success' %></td>
      <td><%= link_to 'Edit', :name => 'submit', :value => 'edit', :class => 'btn btn-warning' %></td>
      <td><%= link_to 'Destroy', :name => 'submit', :value => 'destroy', :class => 'btn btn-danger' %></td>

      <!--<td><%= link_to 'Show', location %></td>
      <td><%= link_to 'Edit', edit_location_path(location) %></td>
      <td><%= link_to 'Destroy', location, :confirm => 'Are you sure?', :method => :delete %></td>-->
    </tr>
  <% end %>
    </tbody>
  </table>

  <br />
  <%= button_tag 'Add', :name => 'submit', :value => 'add', :class => 'btn btn-info' %>
  <%= link_to 'New Location', new_location_path %>
</form>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Location:</b>
  <%= @location.location_id %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.quantity %></td>
    <td><%= product.price %></td>
    <td><%= product.category %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/list.html.erb
<h1>Listing products</h1>

<% @products.each do |product| %>
<div class="alert alert-info">
	<h2><%= link_to "#{product.name}", product %></h2>
	<p><%= "Qty: #{product.quantity} Price: #{product.price}" %></p>
	<p><%= "Category: #{product.category}" %></p>
	<%= link_to 'Add to cart', add_item_path(product.id), :class => 'btn btn-info' %>
</div>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Quantity:</b>
  <%= @product.quantity %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/show_shopping_cart.html.erb
<script type="text/javascript">
  function update_shopping_cart() {

    // Get the table
    var table = document.getElementById("shopping_cart");
    var str = '';

    // Get all elements
    var e = document.forms[0].elements;

    // Iterate without counting the table header
    for ( var elem, i = 0; ( elem = e[i] ); i++ ) {
      if ( elem.type == 'text' ) {
        str += elem.name + ',' + elem.value + '|'
      }
    }

    // Remove the last character
    var newStr = str.substring(0, str.length-1);

    // FIll the hidden field to send it to the controller
    var hidden = document.getElementById('message');
    hidden.value = newStr;
    
    // Submit
    document.forms[0].submit();
  }
</script>

<%= form_tag('/products/update_shopping_cart', :method => :post) do %>
  <%= hidden_field_tag 'message', '' %>
  <table id="shopping_cart" class="table table-bordered">
    <thead>
      <tr>
        <th style='width:200px'>Product Name</th>
        <th style='width:350px'>Description</th>
        <th style='width:40px; text-align: right'>Qty</th>
        <th style='width:70px; text-align: right'>Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
  <% @items.each_with_index do |p, i| %>
    
      <tr>
        <td><%= p.name %></td>
        <td><%= p.description %></td>
        <td><%= text_field_tag "#{p.id}", p.quantity, :class => 'input-qty' %></td>
        <td style='text-align: right'><%= p.price %></td>
        <td>
          <%= link_to 'Delete', delete_item_path(p.id), :confirm => 'Are you sure?', :class => 'btn btn-info' %>
          <%= hidden_field_tag "id_hidden_#{p.id}", p.id %>
        </td>
      </tr>
    
  <% end %>
    </tbody>
  </table>
  <%= submit_tag 'Update', :class => 'btn btn-info',:onclick => "return update_shopping_cart()" %>
  <%= link_to 'Back', root_path, :class => 'btn btn-info' %>
<% end %>